# Tensor

In [10]:
import numpy as np
# 0 dimension = scalar
x = np.array(12)
# 1 dimension = vector
x = np.array([12, 3, 6, 14])
# 2 dimension = matrix
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
# 3 dimension = cube
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])

In [11]:
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [9]:
x.ndim

2

In [12]:
x.shape

(3, 3, 5)

In [13]:
x.dtype

dtype('int32')

In [16]:
x[1:2, :, :]

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [ ]:
# axis 0 = asse delle osservazioni -> importante per il batch size

In [ ]:
output = relu(dot(W, input) + b)

In [32]:
# element-wise operations
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
            
    return x

def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [67]:
import numpy as np
x = np.random.random((10, 5))
y = np.random.random((10, 5))
x + y

for i in np.arange(3):
    test = np.random.normal(0, 0.4, 1)
    print('test')
    print(test)
    print('relu_test')
    print(np.maximum(test, 0))

test
[0.6959113]
relu_test
[0.6959113]
test
[-0.1639217]
relu_test
[0.]
test
[-0.06593987]
relu_test
[0.]


In [68]:
import numpy as np
x = np.random.random((10, 5))
y = np.random.random((5))
print(x)
print(y)

[[3.45072612e-01 5.10272923e-01 6.56857807e-01 2.08339096e-01
  7.99839151e-01]
 [1.39581478e-01 1.54708189e-01 5.90095481e-01 3.90814834e-01
  1.34161080e-01]
 [9.73627153e-01 9.70496435e-01 6.06625148e-01 4.24401238e-01
  6.54462072e-01]
 [7.26757030e-01 5.67355244e-01 8.24626846e-01 9.78556670e-01
  8.55371258e-04]
 [1.07824847e-01 1.31636984e-01 3.61565305e-01 1.32385233e-01
  9.00031106e-01]
 [2.64440717e-01 3.03191629e-01 7.76787083e-01 7.46056684e-01
  4.85712533e-03]
 [1.32116088e-01 5.52885484e-01 2.25748087e-02 5.70736076e-01
  1.16880134e-02]
 [9.94020876e-01 7.14025263e-01 2.92153199e-01 4.69149569e-01
  6.97662868e-01]
 [5.61243286e-01 9.58458073e-01 1.90126322e-01 4.36342246e-01
  1.51260770e-01]
 [5.31874030e-01 2.38172286e-01 6.20444301e-02 1.71003174e-01
  3.38473324e-01]]
[0.32465211 0.6881459  0.20014557 0.77309463 0.12506949]


In [69]:
x + y

array([[0.66972472, 1.19841882, 0.85700337, 0.98143373, 0.92490864],
       [0.46423358, 0.84285409, 0.79024105, 1.16390947, 0.25923057],
       [1.29827926, 1.65864233, 0.80677072, 1.19749587, 0.77953156],
       [1.05140914, 1.25550114, 1.02477241, 1.7516513 , 0.12592486],
       [0.43247695, 0.81978288, 0.56171087, 0.90547987, 1.02510059],
       [0.58909282, 0.99133753, 0.97693265, 1.51915132, 0.12992661],
       [0.45676819, 1.24103138, 0.22272038, 1.34383071, 0.1367575 ],
       [1.31867298, 1.40217116, 0.49229877, 1.2422442 , 0.82273236],
       [0.88589539, 1.64660397, 0.39027189, 1.20943688, 0.27633026],
       [0.85652614, 0.92631818, 0.26219   , 0.94409781, 0.46354281]])

In [87]:
a = np.array([[2,3], [2,3], [2,3]])
b = np.array([[2,3], [2,3]])

In [84]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0], y.shape[1]))
    print(x.shape)
    print(y.shape)
    print(z)
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

In [73]:
a

array([[2, 3],
       [2, 3]])

In [74]:
b

array([[2, 3],
       [2, 3]])

In [77]:
naive_matrix_dot(a, b)

array([[10., 15.],
       [10., 15.]])

In [90]:
x = np.random.random((10, 5))
y = np.random.random((5, 12))

In [91]:
naive_matrix_dot(x, y)

(10, 5)
(5, 12)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[1.66742991, 0.97532945, 1.95508435, 1.95611931, 2.20393385,
        1.47077989, 1.87052302, 1.24784054, 2.44198519, 1.90858416,
        1.08539535, 2.15259251],
       [1.36146216, 0.86957587, 1.60518241, 2.02842554, 1.78177807,
        1.23909987, 1.89407255, 0.87230845, 2.61804212, 1.42979018,
        1.08286301, 2.29211519],
       [0.94303594, 0.77750856, 1.30668709, 1.4346072 , 1.45788962,
        1.11582462, 1.55890659, 0.86337034, 2.12786207, 1.18057525,
        1.00870745, 2.12684077],
       [1.26562579, 0.91162436, 1.46982785, 1.39199053, 1.67710087,
        0.83991386, 1.88440452, 1.30223515, 2.06906033, 1.59002695,
        0.77406415, 1.97472504],
       [1.48122846, 0.92264805, 1.73794202, 1.76194926, 1.96910994,
        1.2880008 , 1.8194819 , 1.11753004, 2.27893833, 1.709132  ,
        0.93153064, 2.01309813],
       [1.1723007 , 0.45102414, 1.10874541, 1.54196631, 1.16138627,
        0.34327928, 1.14999931, 1.03543923, 1.7241834 , 1.11003839,
        0.90747955,

In [80]:
a

array([[2, 3],
       [2, 3]])

In [100]:
x = np.array([[0., 1.], [2., 3.], [4., 5.]])
print(x)
print('----------')
print(x.shape)
print('----------')
x = x.reshape((6, 1))
print(x)
print('----------')
print(x.shape)
print('----------')

[[0. 1.]
 [2. 3.]
 [4. 5.]]
----------
(3, 2)
----------
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
----------
(6, 1)
----------
